//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WPF_ProjectDBEntities : DbContext
    {
        public WPF_ProjectDBEntities()
            : base("name=WPF_ProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInformation> UserInformations { get; set; }
        public virtual DbSet<PetAdoption> PetAdoptions { get; set; }
        public virtual DbSet<PetPostText> PetPostTexts { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Merchandise> Merchandises { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<NormalUserPet> NormalUserPets { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
    }
}
