//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInformation()
        {
            this.NormalUserPets = new HashSet<NormalUserPet>();
        }
    
        public int id { get; set; }
        public string Username { get; set; }
        public byte[] Password { get; set; }
        public byte[] salt { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public byte[] Photo { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int LoginCount { get; set; }
        public string UserType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NormalUserPet> NormalUserPets { get; set; }
    }
}
